batch_size: 322
dropout: 0.75
enable_temporal_sampling: true
epochs: 100
eval_batch_size: 256
eval_trials: 1
num_layers: 2
fanouts:
- 20
- 1
feat_encode_size: 32
hid_size: 256
lr: 0.001
patience: 10
predictor:
  dropout: 0.4
  hid_size: 256
  num_layers: 1
use_multiprocessing: true