lr : 0.001
batch_size : 2048
eval_batch_size : 2048
fanouts : [25, 20]
hid_size : 128
feat_encode_size : 128
dropout : 0.1
epochs: 5
patience: 5
embed_ntypes : []
predictor:
  num_layers: 4
eval_trials: 3
negative_sampling_ratio: 20